version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.0
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password 
      KEYCLOAK_IMPORT: /realm/SpringBootKeycloak-realm-export.json

    ports:
      - 8888:8080
    volumes:
      - ./realm/:/realm

# services:
#   app:
#     image: nginx:alpine
#     volumes:
#       - ./realm:/realm